# Generated by Django 3.2.6 on 2022-05-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.DateTimeField(blank=True, null=True, verbose_name='оплачен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PD', 'оплачен'), ('RDY', 'готов к выдачи'), ('STP', 'отправлен в обработку'), ('FM', 'формируется'), ('PRD', 'обрабатывается'), ('CNC', 'отмена заказа')], default='FM', max_length=3, verbose_name='статус'),
        ),
    ]
