# Generated by Django 3.2.6 on 2022-05-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_auto_20220505_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PD', 'оплачен'), ('FM', 'формируется'), ('RDY', 'готов к выдачи'), ('CNC', 'отмена заказа'), ('PRD', 'обрабатывается'), ('STP', 'отправлен в обработку')], default='FM', max_length=3, verbose_name='статус'),
        ),
    ]
