# Generated by Django 3.2.6 on 2022-05-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RDY', 'готов к выдачи'), ('FM', 'формируется'), ('PD', 'оплачен'), ('PRD', 'обрабатывается'), ('STP', 'отправлен в обработку'), ('CNC', 'отмена заказа')], default='FM', max_length=3, verbose_name='статус'),
        ),
    ]
